In [6]:
import pandas as pd
import seaborn as sns
import numpy as np

#### Question 1
What's the version of NumPy that you installed?

In [2]:
import numpy as np
np.__version__

'1.22.3'

#### Getting the data

In [129]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv') 

#### Question 2
How many records are in the dataset?

In [79]:
df.count().max()

11914

#### Question 3
Who are the most frequent car manufacturers (top-3) according to the dataset?

In [11]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [83]:
df.groupby('Make')['Model'].count().sort_values(ascending=False)[:3]

Make
Chevrolet     1123
Ford           881
Volkswagen     809
Name: Model, dtype: int64

#### Question 4
What's the number of unique Audi car models in the dataset?

In [17]:
df[df.Make=='Audi']['Model'].nunique()

34

#### Question 5
How many columns in the dataset have missing values?

In [131]:
columns_missing  = [col for col in df.columns if df[col].isnull().any()]
columns_missing  

['Engine Fuel Type',
 'Engine HP',
 'Engine Cylinders',
 'Number of Doors',
 'Market Category']

In [132]:
len(columns_missing)

5

#### Question 6
* Find the median value of "Engine Cylinders" column in the dataset.
* Next, calculate the most frequent value of the same "Engine Cylinders".
* Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
* Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?

In [24]:
df['Engine Cylinders'].median()

6.0

In [26]:
df['Engine Cylinders'].fillna(6,inplace=True)

In [27]:
df['Engine Cylinders'].median()

6.0

#### Question 7
* Select all the "Lotus" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. * Let's call the result XTX.
* Invert XTX.
* Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the first element of w?

In [133]:
X = df[df.Make=='Lotus'][['Engine Cylinders','Engine HP']]\
    .drop_duplicates().to_numpy()
X

array([[  4., 189.],
       [  4., 218.],
       [  4., 217.],
       [  8., 350.],
       [  6., 400.],
       [  6., 276.],
       [  6., 345.],
       [  4., 257.],
       [  4., 240.]])

In [134]:
XTX = np.matmul(X.T,X)
XTX

array([[2.52000e+02, 1.34100e+04],
       [1.34100e+04, 7.31684e+05]])

In [135]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv 

array([[ 1.60588447e-01, -2.94319825e-03],
       [-2.94319825e-03,  5.53084235e-05]])

In [136]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [137]:
w = np.matmul(np.matmul(XTX_inv ,X.T),y)
w

array([-63.56432501,   4.59494481])